### ISSUE TITLE
413 Request Entity Too Large debug message

### ISSUE THREAD

**Issue by vitalik** [umputun/reproxy#70]
Would be nice if reproxy throws to debug log message when it returned `413 Request Entity Too Large `

**Comment by umputun** [comment]
reproxy already reports such requests to both access log and stdout log (if enabled). What would be a reason to add another reporting for the same error?

**Comment by vitalik** [comment]
ah.. I thought that DEBUG will print *everything*

maybe it make sense to set automatically `LOGGER_STDOUT=true` when `DEBUG` is `true ` ?

**Comment by umputun** [comment]
I think reporting request status is a part of the logging and status 413 as good/bad as any other. DEBUG/--dbg serves a different purpose - allowing to see some technical details about internal logic if something went wrong.

**Comment by vitalik** [comment]
maybe LOGGER_STDOUT must be default true then ?

my case is the following:

 - I made a test fiel upload in browser
 - got 413
 - looked at my app logs - nothing
 - looked at reproxy logs - nothing (even with debug=true)

I thing all proxy engines by default do dump simple request / reponse-code logs to stdout by default

**Comment by umputun** [comment]
I like less verbose default. In some cases, the user may prefer the access log and may not need to get all the reports messages to stdout. Making users enable one flag and disable another is not the best idea. Another issue with this default change - in most of the cases I have used reproxy myself and a few I'm aware of, the current "silent default" was exactly what needed because services usually report their own logs.

Anyway, I believe the [logging](https://github.com/umputun/reproxy#logging) section in docs covers logging options sufficiently and should be easy to read in case if user wants to turn logging on.
